# Generated by Django 2.2.6 on 2021-02-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='masquerade',
            field=models.BooleanField(help_text='If Yes, then no user information will be present in chat, only the Character Name'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='roleplay',
            field=models.BooleanField(help_text='If Yes, this room is intended for Roleplaying'),
        ),
    ]
